name: Lint, Docker Build and Push to DockerHub

on:
  push:
  pull_request:
    branches: [master, main, dev]

jobs:
  linter:
    name: Lint Code Base - Build Job
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - 
        name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
#   docker:
#     needs: linter
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v1
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       -
#         name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           tags: user/app:latest
